#!/bin/bash
#
# $ maki [role]             [task]
# $ maki [role] [namespace]:[task]
#

export LANG=C
export LC_ALL=C

# global settings

# role

role_solo() {
  nodes() { echo localhost; }
  ssh() { shift; [[ $# == 0 ]] && { eval $SHELL </dev/stdin; } || { eval $@; }; }
}

# namespace:task

namespace_deploy() {
  task_download() {
    local host=${1}; shift
  }

  task_sync() {
    local host=${1}; shift
  }

  task_prepare() {
    local host=${1}; shift
  }

  task_setup() {
    local host=${1}; shift
  }

  task_status() {
    local host=${1}; shift
  }

  task_start() {
    local host=${1}; shift
  }

  task_stop() {
    local host=${1}; shift
  }
}

namespace_service() {
  task_status() {
    local host=${1}; shift

    ssh ${host} bash -ex <<-'EOS'
	sudo service keepalived    status || :
	/sbin/ip addr show
	sudo service mysqld        status || :
	sudo service zabbix-server status || :
	sudo service httpd         status || :
	EOS
  }

  task_on() {
    local host=${1}; shift
  }

  task_off() {
    local host=${1}; shift
  }

  task_start() {
    local host=${1}; shift

    ssh ${host} bash -ex <<-'EOS'
	sudo service keepalived start
	EOS
  }

  task_stop() {
    local host=${1}; shift

    ssh ${host} bash -ex <<-'EOS'
	sudo service keepalived stop || :
	EOS
  }
}

namespace_db() {
  task_init() {
    local host=${1}; shift
  }
}

namespace_logging() {
  task_tail_lines() {
    local host=${1}; shift

    ssh ${host} bash -ex <<-'EOS'
	[[ -f /var/log/messages         ]] && sudo tail -n 20 /var/log/messages
	[[ -f /var/log/mysql/mysqld.log ]] && tail -n 20 /var/log/mysql/mysqld.log
	EOS
  }
}

namespace_test() {
  task_hostname() {
    local host=${1}; shift

    ssh ${host} hostname
  }

  task_date() {
    local host=${1}; shift

    ssh ${host} date
  }

  task_shell() {
    local host=${1}; shift

    ssh ${host} ${@}
  }

  task_run() {
    local host=${1}; shift
  }
}
