# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

BOX_NAME = ENV['BOX_NAME'] || "eieb-executor-x86_64-1503"
BOX_URI  = ENV['BOX_URI']  || "http://eieb.dlc.wakame.axsh.jp/vagrant/eieb-executor/1503/eieb-executor-x86_64-1503.box"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box     = BOX_NAME
  config.vm.box_url = BOX_URI

  script = <<SCRIPT
chmod 600 /opt/axsh/eieb/makistrano/sysvm/keys/eieb-deploy
SCRIPT
  config.vm.provision :shell, :inline => script

  config.vm.provider :virtualbox do |v, override|
   # Disable the base shared folder, guest additions are unavailable.
   #override.vm.synced_folder ".", "/vagrant", disabled: true
   #v.gui = true
   #v.customize ["modifyvm", :id, "--memory", "1024"]

   # [Vagrant / virtualbox DNS 10.0.2.3 not working](http://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working)
   #
   # Enabling DNS proxy in NAT mode
   # > VBoxManage modifyvm "VM name" --natdnsproxy1 on
   # Using the host's resolver as a DNS proxy in NAT mode
   # > VBoxManage modifyvm "VM name" --natdnshostresolver1 on
   #
   v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.ssh.forward_agent = true

  config.vm.network "forwarded_port", guest: 8080, host: 9090, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8081, host: 9091, host_ip: "127.0.0.1"
end
