#!/bin/bash
#
# $ maki [role]             [task]
# $ maki [role] [namespace]:[task]
#

export LANG=C
export LC_ALL=C

# global settings

# role

role_solo() {
  nodes() { echo localhost; }
  ssh() { shift; [[ $# == 0 ]] && { eval $SHELL </dev/stdin; } || { eval $@; }; }
}

role_prototyping() {
  nodes() { echo 10.112.7.14; }
}

# namespace:task

namespace_deploy() {
  task_download() {
    local host=${1}; shift
  }

  task_sync() {
    local host=${1}; shift
  }

  task_prepare() {
    local host=${1}; shift
  }

  task_setup() {
    local host=${1}; shift

    ssh ${host} bash -ex <<-'EOS'
	hostname
	mysqladmin -uroot ping
	mysql -uroot wakame_dcmgr -e 'show tables;' >/dev/null 2>&1 || {
	  mysqladmin -uroot create wakame_dcmgr --default-character-set=utf8
	}
	mysql -uroot <<'_EOS_'
	  grant all privileges on wakame_dcmgr.* to wakame_dcmgr@'%' identified by '********';
	  flush privileges;
	_EOS_
	EOS
  }

  task_status() {
    local host=${1}; shift
  }

  task_start() {
    local host=${1}; shift
  }

  task_stop() {
    local host=${1}; shift
  }
}

namespace_service() {
  task_status() {
    local host=${1}; shift
  }

  task_on() {
    local host=${1}; shift
  }

  task_off() {
    local host=${1}; shift
  }

  task_start() {
    local host=${1}; shift
  }

  task_stop() {
    local host=${1}; shift
  }
}

namespace_db() {
  task_init() {
    local host=${1}; shift
  }
}

namespace_logging() {
  task_tail_lines() {
    local host=${1}; shift
  }
}

namespace_test() {
  task_hostname() {
    local host=${1}; shift

    ssh ${host} hostname
  }

  task_date() {
    local host=${1}; shift

    ssh ${host} date
  }

  task_shell() {
    local host=${1}; shift

    ssh ${host} ${@}
  }

  task_run() {
    local host=${1}; shift
  }
}
